CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_PAD_TOKEN = "[PAD]"
DEFAULT_EOS_TOKEN = "</s>"
DEFAULT_BOS_TOKEN = "</s>"
DEFAULT_UNK_TOKEN = "<unk>"
DEFAULT_IMAGE_TOKEN = "<pc>"
DEFAULT_IMAGE_PATCH_TOKEN = "<pc_patch>"
DEFAULT_IM_START_TOKEN = "<pc_start>"
DEFAULT_IM_END_TOKEN = "<pc_end>"